/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mono;

/**
 *
 * @author dalos
 */
public class Tabla extends javax.swing.JFrame {

    /**
     * Creates new form Tabla
     */
    public Tabla() {
        initCompodsadasdanents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Sarga1 = new javax.swing.JLabel();
        Piros1 = new javax.swing.JLabel();
        Kek1 = new javax.swing.JLabel();
        Zold1 = new javax.swing.JLabel();
        Sarga2 = new javax.swing.JLabel();
        Piros2 = new javax.swing.JLabel();
        Kek2 = new javax.swing.JLabel();
        Zold2 = new javax.swing.JLabel();
        Sarga3 = new javax.swing.JLabel();
        Piros3 = new javax.swing.JLabel();
        Kek3 = new javax.swing.JLabel();
        Zold3 = new javax.swing.JLabel();
        Sarga4 = new javax.swing.JLabel();
        Piros4 = new javax.swing.JLabel();
        Kek4 = new javax.swing.JLabel();
        Zold4 = new javax.swing.JLabel();
        Sarga5 = new javax.swing.JLabel();
        Piros5 = new javax.swing.JLabel();
        Kek5 = new javax.swing.JLabel();
        Zold5 = new javax.swing.JLabel();
        Sarga6 = new javax.swing.JLabel();
        Piros6 = new javax.swing.JLabel();
        Kek6 = new javax.swing.JLabel();
        Zold6 = new javax.swing.JLabel();
        Sarga7 = new javax.swing.JLabel();
        Piros7 = new javax.swing.JLabel();
        Kek7 = new javax.swing.JLabel();
        Zold7 = new javax.swing.JLabel();
        Sarga8 = new javax.swing.JLabel();
        Piros8 = new javax.swing.JLabel();
        Kek8 = new javax.swing.JLabel();
        Zold8 = new javax.swing.JLabel();
        Sarga9 = new javax.swing.JLabel();
        Piros9 = new javax.swing.JLabel();
        Kek9 = new javax.swing.JLabel();
        Zold9 = new javax.swing.JLabel();
        Sarga10 = new javax.swing.JLabel();
        Piros10 = new javax.swing.JLabel();
        Kek10 = new javax.swing.JLabel();
        Zold10 = new javax.swing.JLabel();
        Sarga11 = new javax.swing.JLabel();
        Piros11 = new javax.swing.JLabel();
        Kek11 = new javax.swing.JLabel();
        Zold11 = new javax.swing.JLabel();
        Sarga12 = new javax.swing.JLabel();
        Piros12 = new javax.swing.JLabel();
        Kek12 = new javax.swing.JLabel();
        Zold12 = new javax.swing.JLabel();
        Piros13 = new javax.swing.JLabel();
        Sarga13 = new javax.swing.JLabel();
        Kek13 = new javax.swing.JLabel();
        Zold13 = new javax.swing.JLabel();
        Piros14 = new javax.swing.JLabel();
        Sarga14 = new javax.swing.JLabel();
        Kek14 = new javax.swing.JLabel();
        Zold14 = new javax.swing.JLabel();
        Piros15 = new javax.swing.JLabel();
        Sarga15 = new javax.swing.JLabel();
        Kek15 = new javax.swing.JLabel();
        Zold15 = new javax.swing.JLabel();
        Piros16 = new javax.swing.JLabel();
        Sarga16 = new javax.swing.JLabel();
        Kek16 = new javax.swing.JLabel();
        Zold16 = new javax.swing.JLabel();
        Piros17 = new javax.swing.JLabel();
        Sarga17 = new javax.swing.JLabel();
        Kek17 = new javax.swing.JLabel();
        Zold17 = new javax.swing.JLabel();
        Piros18 = new javax.swing.JLabel();
        Sarga18 = new javax.swing.JLabel();
        Kek18 = new javax.swing.JLabel();
        Zold18 = new javax.swing.JLabel();
        Piros19 = new javax.swing.JLabel();
        Sarga19 = new javax.swing.JLabel();
        Kek19 = new javax.swing.JLabel();
        Zold19 = new javax.swing.JLabel();
        Piros20 = new javax.swing.JLabel();
        Sarga20 = new javax.swing.JLabel();
        Kek20 = new javax.swing.JLabel();
        Zold20 = new javax.swing.JLabel();
        Piros21 = new javax.swing.JLabel();
        Sarga21 = new javax.swing.JLabel();
        Kek21 = new javax.swing.JLabel();
        Zold21 = new javax.swing.JLabel();
        Piros22 = new javax.swing.JLabel();
        Sarga22 = new javax.swing.JLabel();
        Kek22 = new javax.swing.JLabel();
        Zold22 = new javax.swing.JLabel();
        Piros23 = new javax.swing.JLabel();
        Sarga23 = new javax.swing.JLabel();
        Kek23 = new javax.swing.JLabel();
        Zold23 = new javax.swing.JLabel();
        Piros24 = new javax.swing.JLabel();
        Sarga24 = new javax.swing.JLabel();
        Kek24 = new javax.swing.JLabel();
        Zold24 = new javax.swing.JLabel();
        Piros25 = new javax.swing.JLabel();
        Sarga25 = new javax.swing.JLabel();
        Kek25 = new javax.swing.JLabel();
        Zold25 = new javax.swing.JLabel();
        Piros26 = new javax.swing.JLabel();
        Sarga26 = new javax.swing.JLabel();
        Kek26 = new javax.swing.JLabel();
        Zold26 = new javax.swing.JLabel();
        Piros27 = new javax.swing.JLabel();
        Sarga27 = new javax.swing.JLabel();
        Kek27 = new javax.swing.JLabel();
        Zold27 = new javax.swing.JLabel();
        Piros28 = new javax.swing.JLabel();
        Sarga28 = new javax.swing.JLabel();
        Kek28 = new javax.swing.JLabel();
        Zold28 = new javax.swing.JLabel();
        Piros29 = new javax.swing.JLabel();
        Sarga29 = new javax.swing.JLabel();
        Kek29 = new javax.swing.JLabel();
        Zold29 = new javax.swing.JLabel();
        Piros30 = new javax.swing.JLabel();
        Sarga30 = new javax.swing.JLabel();
        Kek30 = new javax.swing.JLabel();
        Zold30 = new javax.swing.JLabel();
        Piros31 = new javax.swing.JLabel();
        Sarga31 = new javax.swing.JLabel();
        Kek31 = new javax.swing.JLabel();
        Zold31 = new javax.swing.JLabel();
        Piros32 = new javax.swing.JLabel();
        Sarga32 = new javax.swing.JLabel();
        Kek32 = new javax.swing.JLabel();
        Zold32 = new javax.swing.JLabel();
        Tabla = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        Sarga1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga1);
        Sarga1.setBounds(650, 40, 28, 45);
        Sarga1.getAccessibleContext().setAccessibleName("Sarga");

        Piros1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros1);
        Piros1.setBounds(680, 40, 28, 45);

        Kek1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek1);
        Kek1.setBounds(680, 10, 28, 45);

        Zold1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold1);
        Zold1.setBounds(650, 10, 28, 45);

        Sarga2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga2);
        Sarga2.setBounds(660, 140, 28, 45);

        Piros2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros2);
        Piros2.setBounds(690, 140, 28, 45);

        Kek2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek2);
        Kek2.setBounds(690, 110, 28, 45);

        Zold2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold2);
        Zold2.setBounds(660, 110, 28, 45);

        Sarga3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga3);
        Sarga3.setBounds(660, 210, 28, 45);

        Piros3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros3);
        Piros3.setBounds(690, 210, 28, 45);

        Kek3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek3);
        Kek3.setBounds(690, 180, 28, 45);

        Zold3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold3);
        Zold3.setBounds(660, 180, 28, 45);

        Sarga4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga4);
        Sarga4.setBounds(660, 280, 28, 45);

        Piros4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros4);
        Piros4.setBounds(690, 280, 28, 45);

        Kek4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek4);
        Kek4.setBounds(690, 250, 28, 45);

        Zold4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold4);
        Zold4.setBounds(660, 250, 28, 45);

        Sarga5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga5);
        Sarga5.setBounds(660, 350, 28, 45);

        Piros5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros5);
        Piros5.setBounds(690, 350, 28, 45);

        Kek5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek5);
        Kek5.setBounds(690, 320, 28, 45);

        Zold5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold5);
        Zold5.setBounds(660, 320, 28, 45);

        Sarga6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga6);
        Sarga6.setBounds(660, 420, 28, 45);

        Piros6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros6);
        Piros6.setBounds(690, 420, 28, 45);

        Kek6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek6);
        Kek6.setBounds(690, 390, 28, 45);

        Zold6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold6);
        Zold6.setBounds(660, 390, 28, 45);

        Sarga7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga7);
        Sarga7.setBounds(660, 490, 28, 45);

        Piros7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros7);
        Piros7.setBounds(690, 490, 28, 45);

        Kek7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek7);
        Kek7.setBounds(690, 460, 28, 45);

        Zold7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold7);
        Zold7.setBounds(660, 460, 28, 45);

        Sarga8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga8);
        Sarga8.setBounds(660, 560, 28, 45);

        Piros8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros8);
        Piros8.setBounds(690, 560, 28, 45);

        Kek8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek8);
        Kek8.setBounds(690, 530, 28, 45);

        Zold8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold8);
        Zold8.setBounds(660, 530, 28, 45);

        Sarga9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga9);
        Sarga9.setBounds(650, 670, 28, 45);

        Piros9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros9);
        Piros9.setBounds(680, 670, 28, 45);

        Kek9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek9);
        Kek9.setBounds(680, 640, 28, 45);

        Zold9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold9);
        Zold9.setBounds(650, 640, 28, 45);

        Sarga10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga10);
        Sarga10.setBounds(540, 670, 28, 45);

        Piros10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros10);
        Piros10.setBounds(570, 670, 28, 45);

        Kek10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek10);
        Kek10.setBounds(570, 640, 28, 45);

        Zold10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold10);
        Zold10.setBounds(540, 640, 28, 45);

        Sarga11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga11);
        Sarga11.setBounds(470, 670, 28, 45);

        Piros11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros11);
        Piros11.setBounds(500, 670, 28, 45);

        Kek11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek11);
        Kek11.setBounds(500, 640, 28, 45);

        Zold11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold11);
        Zold11.setBounds(470, 640, 28, 45);

        Sarga12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga12);
        Sarga12.setBounds(400, 670, 28, 45);

        Piros12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros12);
        Piros12.setBounds(430, 670, 28, 45);

        Kek12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek12);
        Kek12.setBounds(430, 640, 28, 45);

        Zold12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold12);
        Zold12.setBounds(400, 640, 28, 45);

        Piros13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros13);
        Piros13.setBounds(360, 670, 28, 45);

        Sarga13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga13);
        Sarga13.setBounds(330, 670, 28, 45);

        Kek13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek13);
        Kek13.setBounds(360, 640, 28, 45);

        Zold13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold13);
        Zold13.setBounds(330, 640, 28, 45);

        Piros14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros14);
        Piros14.setBounds(290, 670, 28, 45);

        Sarga14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga14);
        Sarga14.setBounds(260, 670, 28, 45);

        Kek14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek14);
        Kek14.setBounds(290, 640, 28, 45);

        Zold14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold14);
        Zold14.setBounds(260, 640, 28, 45);

        Piros15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros15);
        Piros15.setBounds(220, 670, 28, 45);

        Sarga15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga15);
        Sarga15.setBounds(190, 670, 28, 45);

        Kek15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek15);
        Kek15.setBounds(220, 640, 28, 45);

        Zold15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold15);
        Zold15.setBounds(190, 640, 28, 45);

        Piros16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros16);
        Piros16.setBounds(150, 670, 28, 45);

        Sarga16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga16);
        Sarga16.setBounds(120, 670, 28, 45);

        Kek16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek16);
        Kek16.setBounds(150, 640, 28, 45);

        Zold16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold16);
        Zold16.setBounds(120, 640, 28, 45);

        Piros17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros17);
        Piros17.setBounds(40, 670, 28, 45);

        Sarga17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga17);
        Sarga17.setBounds(10, 670, 28, 45);

        Kek17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek17);
        Kek17.setBounds(40, 640, 28, 45);

        Zold17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold17);
        Zold17.setBounds(10, 640, 28, 45);

        Piros18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros18);
        Piros18.setBounds(40, 560, 28, 45);

        Sarga18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga18);
        Sarga18.setBounds(10, 560, 28, 45);

        Kek18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek18);
        Kek18.setBounds(40, 530, 28, 45);

        Zold18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold18);
        Zold18.setBounds(10, 530, 28, 45);

        Piros19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros19);
        Piros19.setBounds(40, 490, 28, 45);

        Sarga19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga19);
        Sarga19.setBounds(10, 490, 28, 45);

        Kek19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek19);
        Kek19.setBounds(40, 460, 28, 45);

        Zold19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold19);
        Zold19.setBounds(10, 460, 28, 45);

        Piros20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros20);
        Piros20.setBounds(40, 420, 28, 45);

        Sarga20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga20);
        Sarga20.setBounds(10, 420, 28, 45);

        Kek20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek20);
        Kek20.setBounds(40, 390, 28, 45);

        Zold20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold20);
        Zold20.setBounds(10, 390, 28, 45);

        Piros21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros21);
        Piros21.setBounds(40, 350, 28, 45);

        Sarga21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga21);
        Sarga21.setBounds(10, 350, 28, 45);

        Kek21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek21);
        Kek21.setBounds(40, 320, 28, 45);

        Zold21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold21);
        Zold21.setBounds(10, 320, 28, 45);

        Piros22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros22);
        Piros22.setBounds(40, 280, 28, 45);

        Sarga22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga22);
        Sarga22.setBounds(10, 280, 28, 45);

        Kek22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek22);
        Kek22.setBounds(40, 250, 28, 45);

        Zold22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold22);
        Zold22.setBounds(10, 250, 28, 45);

        Piros23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros23);
        Piros23.setBounds(40, 210, 28, 45);

        Sarga23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga23);
        Sarga23.setBounds(10, 210, 28, 45);

        Kek23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek23);
        Kek23.setBounds(40, 180, 28, 45);

        Zold23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold23);
        Zold23.setBounds(10, 180, 28, 45);

        Piros24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros24);
        Piros24.setBounds(40, 140, 28, 45);

        Sarga24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga24);
        Sarga24.setBounds(10, 140, 28, 45);

        Kek24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek24);
        Kek24.setBounds(40, 110, 28, 45);

        Zold24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold24);
        Zold24.setBounds(10, 110, 28, 45);

        Piros25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros25);
        Piros25.setBounds(40, 40, 28, 45);

        Sarga25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga25);
        Sarga25.setBounds(10, 40, 28, 45);

        Kek25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek25);
        Kek25.setBounds(40, 10, 28, 45);

        Zold25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold25);
        Zold25.setBounds(10, 10, 28, 45);

        Piros26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros26);
        Piros26.setBounds(150, 40, 28, 45);

        Sarga26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga26);
        Sarga26.setBounds(120, 40, 28, 45);

        Kek26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek26);
        Kek26.setBounds(150, 10, 28, 45);

        Zold26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold26);
        Zold26.setBounds(120, 10, 28, 45);

        Piros27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros27);
        Piros27.setBounds(220, 40, 28, 45);

        Sarga27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga27);
        Sarga27.setBounds(190, 40, 28, 45);

        Kek27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek27);
        Kek27.setBounds(220, 10, 28, 45);

        Zold27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold27);
        Zold27.setBounds(190, 10, 28, 45);

        Piros28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros28);
        Piros28.setBounds(290, 40, 28, 45);

        Sarga28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga28);
        Sarga28.setBounds(260, 40, 28, 45);

        Kek28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek28);
        Kek28.setBounds(290, 10, 28, 45);

        Zold28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold28);
        Zold28.setBounds(260, 10, 28, 45);

        Piros29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros29);
        Piros29.setBounds(360, 40, 28, 45);

        Sarga29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga29);
        Sarga29.setBounds(330, 40, 28, 45);

        Kek29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek29);
        Kek29.setBounds(360, 10, 28, 45);

        Zold29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold29);
        Zold29.setBounds(330, 10, 28, 45);

        Piros30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros30);
        Piros30.setBounds(430, 40, 28, 45);

        Sarga30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga30);
        Sarga30.setBounds(400, 40, 28, 45);

        Kek30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek30);
        Kek30.setBounds(430, 10, 28, 45);

        Zold30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold30);
        Zold30.setBounds(400, 10, 28, 45);

        Piros31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros31);
        Piros31.setBounds(500, 40, 28, 45);

        Sarga31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga31);
        Sarga31.setBounds(470, 40, 28, 45);

        Kek31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek31);
        Kek31.setBounds(500, 10, 28, 45);

        Zold31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold31);
        Zold31.setBounds(470, 10, 28, 45);

        Piros32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros32);
        Piros32.setBounds(570, 40, 28, 45);

        Sarga32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga32);
        Sarga32.setBounds(540, 40, 28, 45);

        Kek32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek32);
        Kek32.setBounds(570, 10, 28, 45);

        Zold32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold32);
        Zold32.setBounds(540, 10, 28, 45);

        Tabla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/tabla.png"))); // NOI18N
        Tabla.setText("jLabel1");
        jPanel1.add(Tabla);
        Tabla.setBounds(0, 0, 730, 723);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 348, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tabla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Kek1;
    private javax.swing.JLabel Kek10;
    private javax.swing.JLabel Kek11;
    private javax.swing.JLabel Kek12;
    private javax.swing.JLabel Kek13;
    private javax.swing.JLabel Kek14;
    private javax.swing.JLabel Kek15;
    private javax.swing.JLabel Kek16;
    private javax.swing.JLabel Kek17;
    private javax.swing.JLabel Kek18;
    private javax.swing.JLabel Kek19;
    private javax.swing.JLabel Kek2;
    private javax.swing.JLabel Kek20;
    private javax.swing.JLabel Kek21;
    private javax.swing.JLabel Kek22;
    private javax.swing.JLabel Kek23;
    private javax.swing.JLabel Kek24;
    private javax.swing.JLabel Kek25;
    private javax.swing.JLabel Kek26;
    private javax.swing.JLabel Kek27;
    private javax.swing.JLabel Kek28;
    private javax.swing.JLabel Kek29;
    private javax.swing.JLabel Kek3;
    private javax.swing.JLabel Kek30;
    private javax.swing.JLabel Kek31;
    private javax.swing.JLabel Kek32;
    private javax.swing.JLabel Kek4;
    private javax.swing.JLabel Kek5;
    private javax.swing.JLabel Kek6;
    private javax.swing.JLabel Kek7;
    private javax.swing.JLabel Kek8;
    private javax.swing.JLabel Kek9;
    private javax.swing.JLabel Piros1;
    private javax.swing.JLabel Piros10;
    private javax.swing.JLabel Piros11;
    private javax.swing.JLabel Piros12;
    private javax.swing.JLabel Piros13;
    private javax.swing.JLabel Piros14;
    private javax.swing.JLabel Piros15;
    private javax.swing.JLabel Piros16;
    private javax.swing.JLabel Piros17;
    private javax.swing.JLabel Piros18;
    private javax.swing.JLabel Piros19;
    private javax.swing.JLabel Piros2;
    private javax.swing.JLabel Piros20;
    private javax.swing.JLabel Piros21;
    private javax.swing.JLabel Piros22;
    private javax.swing.JLabel Piros23;
    private javax.swing.JLabel Piros24;
    private javax.swing.JLabel Piros25;
    private javax.swing.JLabel Piros26;
    private javax.swing.JLabel Piros27;
    private javax.swing.JLabel Piros28;
    private javax.swing.JLabel Piros29;
    private javax.swing.JLabel Piros3;
    private javax.swing.JLabel Piros30;
    private javax.swing.JLabel Piros31;
    private javax.swing.JLabel Piros32;
    private javax.swing.JLabel Piros4;
    private javax.swing.JLabel Piros5;
    private javax.swing.JLabel Piros6;
    private javax.swing.JLabel Piros7;
    private javax.swing.JLabel Piros8;
    private javax.swing.JLabel Piros9;
    private javax.swing.JLabel Sarga1;
    private javax.swing.JLabel Sarga10;
    private javax.swing.JLabel Sarga11;
    private javax.swing.JLabel Sarga12;
    private javax.swing.JLabel Sarga13;
    private javax.swing.JLabel Sarga14;
    private javax.swing.JLabel Sarga15;
    private javax.swing.JLabel Sarga16;
    private javax.swing.JLabel Sarga17;
    private javax.swing.JLabel Sarga18;
    private javax.swing.JLabel Sarga19;
    private javax.swing.JLabel Sarga2;
    private javax.swing.JLabel Sarga20;
    private javax.swing.JLabel Sarga21;
    private javax.swing.JLabel Sarga22;
    private javax.swing.JLabel Sarga23;
    private javax.swing.JLabel Sarga24;
    private javax.swing.JLabel Sarga25;
    private javax.swing.JLabel Sarga26;
    private javax.swing.JLabel Sarga27;
    private javax.swing.JLabel Sarga28;
    private javax.swing.JLabel Sarga29;
    private javax.swing.JLabel Sarga3;
    private javax.swing.JLabel Sarga30;
    private javax.swing.JLabel Sarga31;
    private javax.swing.JLabel Sarga32;
    private javax.swing.JLabel Sarga4;
    private javax.swing.JLabel Sarga5;
    private javax.swing.JLabel Sarga6;
    private javax.swing.JLabel Sarga7;
    private javax.swing.JLabel Sarga8;
    private javax.swing.JLabel Sarga9;
    private javax.swing.JLabel Tabla;
    private javax.swing.JLabel Zold1;
    private javax.swing.JLabel Zold10;
    private javax.swing.JLabel Zold11;
    private javax.swing.JLabel Zold12;
    private javax.swing.JLabel Zold13;
    private javax.swing.JLabel Zold14;
    private javax.swing.JLabel Zold15;
    private javax.swing.JLabel Zold16;
    private javax.swing.JLabel Zold17;
    private javax.swing.JLabel Zold18;
    private javax.swing.JLabel Zold19;
    private javax.swing.JLabel Zold2;
    private javax.swing.JLabel Zold20;
    private javax.swing.JLabel Zold21;
    private javax.swing.JLabel Zold22;
    private javax.swing.JLabel Zold23;
    private javax.swing.JLabel Zold24;
    private javax.swing.JLabel Zold25;
    private javax.swing.JLabel Zold26;
    private javax.swing.JLabel Zold27;
    private javax.swing.JLabel Zold28;
    private javax.swing.JLabel Zold29;
    private javax.swing.JLabel Zold3;
    private javax.swing.JLabel Zold30;
    private javax.swing.JLabel Zold31;
    private javax.swing.JLabel Zold32;
    private javax.swing.JLabel Zold4;
    private javax.swing.JLabel Zold5;
    private javax.swing.JLabel Zold6;
    private javax.swing.JLabel Zold7;
    private javax.swing.JLabel Zold8;
    private javax.swing.JLabel Zold9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
