/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mono;

/**
 * A Játékszabály frame megjelenítéséért felelős osztály.
 * @author IP
 */
public class Informacio extends javax.swing.JFrame {

    private int mouseX;
    private int mouseY;
    
    public Informacio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kilepesGomb = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane5 = new javax.swing.JTextPane();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(null);

        kilepesGomb.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        kilepesGomb.setForeground(new java.awt.Color(255, 255, 255));
        kilepesGomb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kilepesGomb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/Actions-window-close-icon.png"))); // NOI18N
        kilepesGomb.setToolTipText("Bezár");
        kilepesGomb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kilepesGomb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kilepesGombMouseClicked(evt);
            }
        });
        jPanel1.add(kilepesGomb);
        kilepesGomb.setBounds(517, 7, 30, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kicsi_logo.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(140, 10, 275, 125);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("JÁTÉKSZABÁLY");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(180, 150, 190, 27);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Jó szórakozást kívánunk!");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 740, 550, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("A játék célja:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 190, 100, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("- rendkívüli ösztöndíj: +10");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(260, 510, 150, 20);

        jScrollPane1.setBorder(null);

        jTextPane1.setEditable(false);
        jTextPane1.setBorder(null);
        jTextPane1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextPane1.setText("- Amennyiben a játékos egy még megvásárolható mezőre lép, akkor dönthet arról, hogy szeretné-e megvenni azt. Ekkor kifizeti érte a szükséges mennyiségű kreditet.");
        jTextPane1.setToolTipText("");
        jScrollPane1.setViewportView(jTextPane1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 370, 510, 30);

        jScrollPane2.setBorder(null);

        jTextPane2.setEditable(false);
        jTextPane2.setBorder(null);
        jTextPane2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextPane2.setText("A játékosok a kezdőképernyőn megadott névsorrendben következnek egymás után. A soron következő játékos az alábbiakat hajtja végre:");
        jTextPane2.setToolTipText("");
        jScrollPane2.setViewportView(jTextPane2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(20, 260, 510, 30);

        jScrollPane3.setBorder(null);

        jTextPane3.setEditable(false);
        jTextPane3.setBorder(null);
        jTextPane3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextPane3.setText("- A dobókockára kattintva dob, ennek megfelelően lép a táblán.");
        jTextPane3.setToolTipText("");
        jScrollPane3.setViewportView(jTextPane3);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(20, 300, 510, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("A játék menete:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 240, 130, 17);

        jScrollPane5.setBorder(null);

        jTextPane5.setEditable(false);
        jTextPane5.setBorder(null);
        jTextPane5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextPane5.setText("- Amennyiben egy nem megvásárolható mezőre lép a játékos, annak hatása automatikusan végrehajtásra kerül, pl. Neptun kártya. Ha egy olyan birtokolható mezőre lép, amit már megvásárolt valaki, akkor kifizeti részére a mezőhöz tartozó kreditmennyiséget.");
        jTextPane5.setToolTipText("");
        jScrollPane5.setViewportView(jTextPane5);

        jPanel1.add(jScrollPane5);
        jScrollPane5.setBounds(20, 320, 510, 50);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("A játék akkor ér véget, a egy játékos összegyűjt 180 kreditet, és ezzel megszerzi a diplomát.");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 210, 500, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("- kávéautomata: -3");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 430, 120, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("- italautomata: -4");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 450, 120, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("- menza: -5");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(20, 470, 120, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("- elégtelen: -8");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(20, 490, 150, 20);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("- könyvtár (12/9)");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(20, 700, 230, 20);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("- jegyzetek: +3");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(260, 430, 160, 20);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("- beadandó: +4");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(260, 450, 120, 20);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("- online zárthelyi: +5");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(260, 470, 120, 20);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("- tárgy elismerve: +8");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(260, 490, 120, 20);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Mezők kreditértékei:");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(20, 410, 160, 17);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Mezők kreditértékei:");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(20, 410, 160, 17);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("- zárthelyi: +1 és 5 között");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(20, 510, 230, 20);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Hegylakók © 2021");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(0, 770, 550, 20);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("- porta (3/3)");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(20, 580, 230, 20);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setText("- lift (5/4)");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(20, 600, 230, 20);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("- HÖK iroda (6/4)");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(20, 620, 230, 20);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setText("- sportpálya (8/6)");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(20, 640, 230, 20);

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel25.setText("- konditerem (10/8)");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(20, 660, 230, 20);

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel26.setText("- robotika labor (12/9)");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(20, 680, 230, 20);

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel27.setText("- ping-pong asztal (2/2)");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(20, 560, 230, 20);

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel28.setText("- tanulmányi hivatal (14/10)");
        jPanel1.add(jLabel28);
        jLabel28.setBounds(260, 560, 230, 20);

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel29.setText("- informatika terem (14/10)");
        jPanel1.add(jLabel29);
        jLabel29.setBounds(260, 580, 230, 20);

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel30.setText("- nagyelőadó (16/12)");
        jPanel1.add(jLabel30);
        jLabel30.setBounds(260, 600, 230, 20);

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel31.setText("- díszterem (18/14)");
        jPanel1.add(jLabel31);
        jLabel31.setBounds(260, 620, 230, 20);

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel32.setText("- tornaterem (20/15)");
        jPanel1.add(jLabel32);
        jLabel32.setBounds(260, 640, 230, 20);

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel33.setText("- B-Club (20/16)");
        jPanel1.add(jLabel33);
        jLabel33.setBounds(260, 660, 230, 20);

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel34.setText("- gépész labor (22/17)");
        jPanel1.add(jLabel34);
        jLabel34.setBounds(260, 680, 230, 20);

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel35.setText("Megvásárolható mezők (vételi ár/beszedhető kredit):");
        jPanel1.add(jLabel35);
        jLabel35.setBounds(20, 540, 400, 17);

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel36.setText("- ELTE Shop (24/18)");
        jPanel1.add(jLabel36);
        jLabel36.setBounds(260, 700, 230, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kilepesGombMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kilepesGombMouseClicked
        setVisible(false);
    }//GEN-LAST:event_kilepesGombMouseClicked

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        setLocation(getX() + evt.getX() - mouseX, getY() + evt.getY() - mouseY);
    }//GEN-LAST:event_jPanel1MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Informacio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Informacio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Informacio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Informacio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Informacio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JTextPane jTextPane5;
    private javax.swing.JLabel kilepesGomb;
    // End of variables declaration//GEN-END:variables
}
