/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mono;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.Random;
import java.util.concurrent.TimeUnit;

/**
 * A tábla grafikus megjelenítéséért felelős osztály.
 * @author dalos
 */
public class Tabla extends javax.swing.JFrame {

    private int mouseX;
    private int mouseY;

    /**
     * Creates new form Tabla
     */
    public Tabla() {
        initComponents();
        buildCollections();
        Start.model.kezdoPoziciok();
        rajzolBabuk(Start.model.poz());
        jatekos.setText((String) Start.model.getName());
        kredit.setText(String.valueOf(Start.model.getKredit()));
        vasarlas.setVisible(false);
        kovetkezojatekosgomb.setVisible(false);

        kockaForog();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hatter = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Sarga1 = new javax.swing.JLabel();
        Piros1 = new javax.swing.JLabel();
        Kek1 = new javax.swing.JLabel();
        Zold1 = new javax.swing.JLabel();
        Sarga2 = new javax.swing.JLabel();
        Piros2 = new javax.swing.JLabel();
        Kek2 = new javax.swing.JLabel();
        Zold2 = new javax.swing.JLabel();
        Sarga3 = new javax.swing.JLabel();
        Piros3 = new javax.swing.JLabel();
        Kek3 = new javax.swing.JLabel();
        Zold3 = new javax.swing.JLabel();
        Sarga4 = new javax.swing.JLabel();
        Piros4 = new javax.swing.JLabel();
        Kek4 = new javax.swing.JLabel();
        Zold4 = new javax.swing.JLabel();
        Sarga5 = new javax.swing.JLabel();
        Piros5 = new javax.swing.JLabel();
        Kek5 = new javax.swing.JLabel();
        Zold5 = new javax.swing.JLabel();
        Sarga6 = new javax.swing.JLabel();
        Piros6 = new javax.swing.JLabel();
        Kek6 = new javax.swing.JLabel();
        Zold6 = new javax.swing.JLabel();
        Sarga7 = new javax.swing.JLabel();
        Piros7 = new javax.swing.JLabel();
        Kek7 = new javax.swing.JLabel();
        Zold7 = new javax.swing.JLabel();
        Sarga8 = new javax.swing.JLabel();
        Piros8 = new javax.swing.JLabel();
        Kek8 = new javax.swing.JLabel();
        Zold8 = new javax.swing.JLabel();
        Sarga9 = new javax.swing.JLabel();
        Piros9 = new javax.swing.JLabel();
        Kek9 = new javax.swing.JLabel();
        Zold9 = new javax.swing.JLabel();
        Sarga10 = new javax.swing.JLabel();
        Piros10 = new javax.swing.JLabel();
        Kek10 = new javax.swing.JLabel();
        Zold10 = new javax.swing.JLabel();
        Sarga11 = new javax.swing.JLabel();
        Piros11 = new javax.swing.JLabel();
        Kek11 = new javax.swing.JLabel();
        Zold11 = new javax.swing.JLabel();
        Sarga12 = new javax.swing.JLabel();
        Piros12 = new javax.swing.JLabel();
        Kek12 = new javax.swing.JLabel();
        Zold12 = new javax.swing.JLabel();
        Piros13 = new javax.swing.JLabel();
        Sarga13 = new javax.swing.JLabel();
        Kek13 = new javax.swing.JLabel();
        Zold13 = new javax.swing.JLabel();
        Piros14 = new javax.swing.JLabel();
        Sarga14 = new javax.swing.JLabel();
        Kek14 = new javax.swing.JLabel();
        Zold14 = new javax.swing.JLabel();
        Piros15 = new javax.swing.JLabel();
        Sarga15 = new javax.swing.JLabel();
        Kek15 = new javax.swing.JLabel();
        Zold15 = new javax.swing.JLabel();
        Piros16 = new javax.swing.JLabel();
        Sarga16 = new javax.swing.JLabel();
        Kek16 = new javax.swing.JLabel();
        Zold16 = new javax.swing.JLabel();
        Piros17 = new javax.swing.JLabel();
        Sarga17 = new javax.swing.JLabel();
        Kek17 = new javax.swing.JLabel();
        Zold17 = new javax.swing.JLabel();
        Piros18 = new javax.swing.JLabel();
        Sarga18 = new javax.swing.JLabel();
        Kek18 = new javax.swing.JLabel();
        Zold18 = new javax.swing.JLabel();
        Piros19 = new javax.swing.JLabel();
        Sarga19 = new javax.swing.JLabel();
        Kek19 = new javax.swing.JLabel();
        Zold19 = new javax.swing.JLabel();
        Piros20 = new javax.swing.JLabel();
        Sarga20 = new javax.swing.JLabel();
        Kek20 = new javax.swing.JLabel();
        Zold20 = new javax.swing.JLabel();
        Piros21 = new javax.swing.JLabel();
        Sarga21 = new javax.swing.JLabel();
        Kek21 = new javax.swing.JLabel();
        Zold21 = new javax.swing.JLabel();
        Piros22 = new javax.swing.JLabel();
        Sarga22 = new javax.swing.JLabel();
        Kek22 = new javax.swing.JLabel();
        Zold22 = new javax.swing.JLabel();
        Piros23 = new javax.swing.JLabel();
        Sarga23 = new javax.swing.JLabel();
        Kek23 = new javax.swing.JLabel();
        Zold23 = new javax.swing.JLabel();
        Piros24 = new javax.swing.JLabel();
        Sarga24 = new javax.swing.JLabel();
        Kek24 = new javax.swing.JLabel();
        Zold24 = new javax.swing.JLabel();
        Piros25 = new javax.swing.JLabel();
        Sarga25 = new javax.swing.JLabel();
        Kek25 = new javax.swing.JLabel();
        Zold25 = new javax.swing.JLabel();
        Piros26 = new javax.swing.JLabel();
        Sarga26 = new javax.swing.JLabel();
        Kek26 = new javax.swing.JLabel();
        Zold26 = new javax.swing.JLabel();
        Piros27 = new javax.swing.JLabel();
        Sarga27 = new javax.swing.JLabel();
        Kek27 = new javax.swing.JLabel();
        Zold27 = new javax.swing.JLabel();
        Piros28 = new javax.swing.JLabel();
        Sarga28 = new javax.swing.JLabel();
        Kek28 = new javax.swing.JLabel();
        Zold28 = new javax.swing.JLabel();
        Piros29 = new javax.swing.JLabel();
        Sarga29 = new javax.swing.JLabel();
        Kek29 = new javax.swing.JLabel();
        Zold29 = new javax.swing.JLabel();
        Piros30 = new javax.swing.JLabel();
        Sarga30 = new javax.swing.JLabel();
        Kek30 = new javax.swing.JLabel();
        Zold30 = new javax.swing.JLabel();
        Piros31 = new javax.swing.JLabel();
        Sarga31 = new javax.swing.JLabel();
        Kek31 = new javax.swing.JLabel();
        Zold31 = new javax.swing.JLabel();
        Piros32 = new javax.swing.JLabel();
        Sarga32 = new javax.swing.JLabel();
        Kek32 = new javax.swing.JLabel();
        Zold32 = new javax.swing.JLabel();
        Mezo2 = new javax.swing.JLabel();
        Mezo4 = new javax.swing.JLabel();
        Mezo6 = new javax.swing.JLabel();
        Mezo8 = new javax.swing.JLabel();
        Mezo10 = new javax.swing.JLabel();
        Mezo12 = new javax.swing.JLabel();
        Mezo14 = new javax.swing.JLabel();
        Mezo16 = new javax.swing.JLabel();
        Mezo18 = new javax.swing.JLabel();
        Mezo20 = new javax.swing.JLabel();
        Mezo22 = new javax.swing.JLabel();
        Mezo24 = new javax.swing.JLabel();
        Mezo26 = new javax.swing.JLabel();
        Mezo28 = new javax.swing.JLabel();
        Mezo30 = new javax.swing.JLabel();
        Mezo32 = new javax.swing.JLabel();
        dobokocka = new javax.swing.JLabel();
        neptunUzenet = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Tabla = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        kezdokerdit1 = new javax.swing.JPanel();
        mezonev = new javax.swing.JLabel();
        kezdokerdit = new javax.swing.JLabel();
        kredit = new javax.swing.JLabel();
        jatekos = new javax.swing.JLabel();
        vasarlas = new javax.swing.JLabel();
        kovetkezojatekosgomb = new javax.swing.JLabel();
        vasarlasara = new javax.swing.JLabel();
        birtokoltmezoszama = new javax.swing.JLabel();
        nevkiir = new javax.swing.JLabel();
        kezdokerdit2 = new javax.swing.JLabel();
        birtokoltmezo = new javax.swing.JLabel();
        kilepesPanel = new javax.swing.JPanel();
        kilepesGomb = new javax.swing.JLabel();
        infoGomb = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        hatter.setBackground(new java.awt.Color(255, 255, 255));
        hatter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        Sarga1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga1);
        Sarga1.setBounds(650, 40, 24, 40);
        Sarga1.getAccessibleContext().setAccessibleName("Sarga");

        Piros1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros1);
        Piros1.setBounds(680, 40, 24, 40);

        Kek1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek1);
        Kek1.setBounds(680, 10, 24, 40);

        Zold1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold1);
        Zold1.setBounds(650, 10, 24, 40);

        Sarga2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga2);
        Sarga2.setBounds(660, 140, 24, 40);

        Piros2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros2);
        Piros2.setBounds(690, 140, 24, 40);

        Kek2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek2);
        Kek2.setBounds(690, 110, 24, 40);

        Zold2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold2);
        Zold2.setBounds(660, 110, 24, 40);

        Sarga3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga3);
        Sarga3.setBounds(660, 210, 24, 40);

        Piros3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros3);
        Piros3.setBounds(690, 210, 24, 40);

        Kek3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek3);
        Kek3.setBounds(690, 180, 24, 40);

        Zold3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold3);
        Zold3.setBounds(660, 180, 24, 40);

        Sarga4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga4);
        Sarga4.setBounds(660, 280, 24, 40);

        Piros4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros4);
        Piros4.setBounds(690, 280, 24, 40);

        Kek4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek4);
        Kek4.setBounds(690, 250, 24, 40);

        Zold4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold4);
        Zold4.setBounds(660, 250, 24, 40);

        Sarga5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga5);
        Sarga5.setBounds(660, 350, 24, 40);

        Piros5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros5);
        Piros5.setBounds(690, 350, 24, 40);

        Kek5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek5);
        Kek5.setBounds(690, 320, 24, 40);

        Zold5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold5);
        Zold5.setBounds(660, 320, 24, 40);

        Sarga6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga6);
        Sarga6.setBounds(660, 420, 24, 40);

        Piros6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros6);
        Piros6.setBounds(690, 420, 24, 40);

        Kek6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek6);
        Kek6.setBounds(690, 390, 24, 40);

        Zold6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold6);
        Zold6.setBounds(660, 390, 24, 40);

        Sarga7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga7);
        Sarga7.setBounds(660, 490, 24, 40);

        Piros7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros7);
        Piros7.setBounds(690, 490, 24, 40);

        Kek7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek7);
        Kek7.setBounds(690, 460, 24, 40);

        Zold7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold7);
        Zold7.setBounds(660, 460, 24, 40);

        Sarga8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga8);
        Sarga8.setBounds(660, 560, 24, 40);

        Piros8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros8);
        Piros8.setBounds(690, 560, 24, 40);

        Kek8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek8);
        Kek8.setBounds(690, 530, 24, 40);

        Zold8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold8);
        Zold8.setBounds(660, 530, 24, 40);

        Sarga9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga9);
        Sarga9.setBounds(650, 670, 24, 40);

        Piros9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros9);
        Piros9.setBounds(680, 670, 24, 40);

        Kek9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek9);
        Kek9.setBounds(680, 640, 24, 40);

        Zold9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold9);
        Zold9.setBounds(650, 640, 24, 40);

        Sarga10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga10);
        Sarga10.setBounds(540, 670, 24, 40);

        Piros10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros10);
        Piros10.setBounds(570, 670, 24, 40);

        Kek10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek10);
        Kek10.setBounds(570, 640, 24, 40);

        Zold10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold10);
        Zold10.setBounds(540, 640, 24, 40);

        Sarga11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga11);
        Sarga11.setBounds(470, 670, 24, 40);

        Piros11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros11);
        Piros11.setBounds(500, 670, 24, 40);

        Kek11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek11);
        Kek11.setBounds(500, 640, 24, 40);

        Zold11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold11);
        Zold11.setBounds(470, 640, 24, 40);

        Sarga12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga12);
        Sarga12.setBounds(400, 670, 24, 40);

        Piros12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros12);
        Piros12.setBounds(430, 670, 24, 40);

        Kek12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek12);
        Kek12.setBounds(430, 640, 24, 40);

        Zold12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold12);
        Zold12.setBounds(400, 640, 24, 40);

        Piros13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros13);
        Piros13.setBounds(360, 670, 24, 40);

        Sarga13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga13);
        Sarga13.setBounds(330, 670, 24, 40);

        Kek13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek13);
        Kek13.setBounds(360, 640, 24, 40);

        Zold13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold13);
        Zold13.setBounds(330, 640, 24, 40);

        Piros14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros14);
        Piros14.setBounds(290, 670, 24, 40);

        Sarga14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga14);
        Sarga14.setBounds(260, 670, 24, 40);

        Kek14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek14);
        Kek14.setBounds(290, 640, 24, 40);

        Zold14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold14);
        Zold14.setBounds(260, 640, 24, 40);

        Piros15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros15);
        Piros15.setBounds(220, 670, 24, 40);

        Sarga15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga15);
        Sarga15.setBounds(190, 670, 24, 40);

        Kek15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek15);
        Kek15.setBounds(220, 640, 24, 40);

        Zold15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold15);
        Zold15.setBounds(190, 640, 24, 40);

        Piros16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros16);
        Piros16.setBounds(150, 670, 24, 40);

        Sarga16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga16);
        Sarga16.setBounds(120, 670, 24, 40);

        Kek16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek16);
        Kek16.setBounds(150, 640, 24, 40);

        Zold16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold16);
        Zold16.setBounds(120, 640, 24, 40);

        Piros17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros17);
        Piros17.setBounds(40, 670, 24, 40);

        Sarga17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga17);
        Sarga17.setBounds(10, 670, 24, 40);

        Kek17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek17);
        Kek17.setBounds(40, 640, 24, 40);

        Zold17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold17);
        Zold17.setBounds(10, 640, 24, 40);

        Piros18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros18);
        Piros18.setBounds(40, 560, 24, 40);

        Sarga18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga18);
        Sarga18.setBounds(10, 560, 24, 40);

        Kek18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek18);
        Kek18.setBounds(40, 530, 24, 40);

        Zold18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold18);
        Zold18.setBounds(10, 530, 24, 40);

        Piros19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros19);
        Piros19.setBounds(40, 490, 24, 40);

        Sarga19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga19);
        Sarga19.setBounds(10, 490, 24, 40);

        Kek19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek19);
        Kek19.setBounds(40, 460, 24, 40);

        Zold19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold19);
        Zold19.setBounds(10, 460, 24, 40);

        Piros20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros20);
        Piros20.setBounds(40, 420, 24, 40);

        Sarga20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga20);
        Sarga20.setBounds(10, 420, 24, 40);

        Kek20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek20);
        Kek20.setBounds(40, 390, 24, 40);

        Zold20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold20);
        Zold20.setBounds(10, 390, 24, 40);

        Piros21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros21);
        Piros21.setBounds(40, 350, 24, 40);

        Sarga21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga21);
        Sarga21.setBounds(10, 350, 24, 40);

        Kek21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek21);
        Kek21.setBounds(40, 320, 24, 40);

        Zold21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold21);
        Zold21.setBounds(10, 320, 24, 40);

        Piros22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros22);
        Piros22.setBounds(40, 280, 24, 40);

        Sarga22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga22);
        Sarga22.setBounds(10, 280, 24, 40);

        Kek22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek22);
        Kek22.setBounds(40, 250, 24, 40);

        Zold22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold22);
        Zold22.setBounds(10, 250, 24, 40);

        Piros23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros23);
        Piros23.setBounds(40, 210, 24, 40);

        Sarga23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga23);
        Sarga23.setBounds(10, 210, 24, 40);

        Kek23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek23);
        Kek23.setBounds(40, 180, 24, 40);

        Zold23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold23);
        Zold23.setBounds(10, 180, 24, 40);

        Piros24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros24);
        Piros24.setBounds(40, 140, 24, 40);

        Sarga24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga24);
        Sarga24.setBounds(10, 140, 24, 40);

        Kek24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek24);
        Kek24.setBounds(40, 110, 24, 40);

        Zold24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold24);
        Zold24.setBounds(10, 110, 24, 40);

        Piros25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros25);
        Piros25.setBounds(40, 40, 24, 40);

        Sarga25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga25);
        Sarga25.setBounds(10, 40, 24, 40);

        Kek25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek25);
        Kek25.setBounds(40, 10, 24, 40);

        Zold25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold25);
        Zold25.setBounds(10, 10, 24, 40);

        Piros26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros26);
        Piros26.setBounds(150, 40, 24, 40);

        Sarga26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga26);
        Sarga26.setBounds(120, 40, 24, 40);

        Kek26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek26);
        Kek26.setBounds(150, 10, 24, 40);

        Zold26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold26);
        Zold26.setBounds(120, 10, 24, 40);

        Piros27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros27);
        Piros27.setBounds(220, 40, 24, 40);

        Sarga27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga27);
        Sarga27.setBounds(190, 40, 24, 40);

        Kek27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek27);
        Kek27.setBounds(220, 10, 24, 40);

        Zold27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold27);
        Zold27.setBounds(190, 10, 24, 40);

        Piros28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros28);
        Piros28.setBounds(290, 40, 24, 40);

        Sarga28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga28);
        Sarga28.setBounds(260, 40, 24, 40);

        Kek28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek28);
        Kek28.setBounds(290, 10, 24, 40);

        Zold28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold28);
        Zold28.setBounds(260, 10, 24, 40);

        Piros29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros29);
        Piros29.setBounds(360, 40, 24, 40);

        Sarga29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga29);
        Sarga29.setBounds(330, 40, 24, 40);

        Kek29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek29);
        Kek29.setBounds(360, 10, 24, 40);

        Zold29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold29);
        Zold29.setBounds(330, 10, 24, 40);

        Piros30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros30);
        Piros30.setBounds(430, 40, 24, 40);

        Sarga30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga30);
        Sarga30.setBounds(400, 40, 24, 40);

        Kek30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek30);
        Kek30.setBounds(430, 10, 24, 40);

        Zold30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold30);
        Zold30.setBounds(400, 10, 24, 40);

        Piros31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros31);
        Piros31.setBounds(500, 40, 24, 40);

        Sarga31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga31);
        Sarga31.setBounds(470, 40, 24, 40);

        Kek31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek31);
        Kek31.setBounds(500, 10, 24, 40);

        Zold31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold31);
        Zold31.setBounds(470, 10, 24, 40);

        Piros32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/piros.png"))); // NOI18N
        jPanel1.add(Piros32);
        Piros32.setBounds(570, 40, 24, 40);

        Sarga32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/sarga.png"))); // NOI18N
        jPanel1.add(Sarga32);
        Sarga32.setBounds(540, 40, 24, 40);

        Kek32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kek.png"))); // NOI18N
        jPanel1.add(Kek32);
        Kek32.setBounds(570, 10, 24, 40);

        Zold32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/zold.png"))); // NOI18N
        jPanel1.add(Zold32);
        Zold32.setBounds(540, 10, 24, 40);

        Mezo2.setBackground(new java.awt.Color(255, 255, 255));
        Mezo2.setOpaque(true);
        jPanel1.add(Mezo2);
        Mezo2.setBounds(608, 118, 29, 67);

        Mezo4.setBackground(new java.awt.Color(255, 255, 255));
        Mezo4.setOpaque(true);
        jPanel1.add(Mezo4);
        Mezo4.setBounds(608, 258, 29, 67);

        Mezo6.setBackground(new java.awt.Color(255, 255, 255));
        Mezo6.setOpaque(true);
        jPanel1.add(Mezo6);
        Mezo6.setBounds(608, 398, 29, 67);

        Mezo8.setBackground(new java.awt.Color(255, 255, 255));
        Mezo8.setOpaque(true);
        jPanel1.add(Mezo8);
        Mezo8.setBounds(608, 538, 29, 67);

        Mezo10.setBackground(new java.awt.Color(255, 255, 255));
        Mezo10.setOpaque(true);
        jPanel1.add(Mezo10);
        Mezo10.setBounds(538, 608, 67, 24);

        Mezo12.setBackground(new java.awt.Color(255, 255, 255));
        Mezo12.setOpaque(true);
        jPanel1.add(Mezo12);
        Mezo12.setBounds(398, 608, 67, 24);

        Mezo14.setBackground(new java.awt.Color(255, 255, 255));
        Mezo14.setOpaque(true);
        jPanel1.add(Mezo14);
        Mezo14.setBounds(258, 608, 67, 24);

        Mezo16.setBackground(new java.awt.Color(255, 255, 255));
        Mezo16.setOpaque(true);
        jPanel1.add(Mezo16);
        Mezo16.setBounds(118, 608, 67, 24);

        Mezo18.setBackground(new java.awt.Color(255, 255, 255));
        Mezo18.setOpaque(true);
        jPanel1.add(Mezo18);
        Mezo18.setBounds(90, 538, 25, 67);

        Mezo20.setBackground(new java.awt.Color(255, 255, 255));
        Mezo20.setOpaque(true);
        jPanel1.add(Mezo20);
        Mezo20.setBounds(90, 398, 25, 67);

        Mezo22.setBackground(new java.awt.Color(255, 255, 255));
        Mezo22.setOpaque(true);
        jPanel1.add(Mezo22);
        Mezo22.setBounds(90, 258, 25, 67);

        Mezo24.setBackground(new java.awt.Color(255, 255, 255));
        Mezo24.setOpaque(true);
        jPanel1.add(Mezo24);
        Mezo24.setBounds(90, 118, 25, 67);

        Mezo26.setBackground(new java.awt.Color(255, 255, 255));
        Mezo26.setOpaque(true);
        jPanel1.add(Mezo26);
        Mezo26.setBounds(118, 89, 67, 26);

        Mezo28.setBackground(new java.awt.Color(255, 255, 255));
        Mezo28.setOpaque(true);
        jPanel1.add(Mezo28);
        Mezo28.setBounds(258, 89, 67, 26);

        Mezo30.setBackground(new java.awt.Color(255, 255, 255));
        Mezo30.setOpaque(true);
        jPanel1.add(Mezo30);
        Mezo30.setBounds(398, 89, 67, 26);

        Mezo32.setBackground(new java.awt.Color(255, 255, 255));
        Mezo32.setOpaque(true);
        jPanel1.add(Mezo32);
        Mezo32.setBounds(538, 89, 67, 26);

        dobokocka.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/egy.png"))); // NOI18N
        dobokocka.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dobokocka.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dobokockaMouseClicked(evt);
            }
        });
        jPanel1.add(dobokocka);
        dobokocka.setBounds(450, 480, 73, 70);

        neptunUzenet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/neptunkartya.png"))); // NOI18N
        neptunUzenet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                neptunUzenetMouseClicked(evt);
            }
        });
        jPanel1.add(neptunUzenet);
        neptunUzenet.setBounds(170, 160, 170, 93);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/dobokovkafelirat.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(320, 420, 200, 110);

        Tabla.setBackground(new java.awt.Color(255, 255, 255));
        Tabla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/tablalogok.jpg"))); // NOI18N
        Tabla.setText("jLabel1");
        jPanel1.add(Tabla);
        Tabla.setBounds(0, 0, 730, 723);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        kezdokerdit1.setBackground(new java.awt.Color(255, 255, 255));
        kezdokerdit1.setLayout(null);

        mezonev.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        mezonev.setForeground(new java.awt.Color(204, 0, 0));
        mezonev.setText("Start!");
        mezonev.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        kezdokerdit1.add(mezonev);
        mezonev.setBounds(170, 340, 190, 110);

        kezdokerdit.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        kezdokerdit.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        kezdokerdit.setText("Mező:");
        kezdokerdit1.add(kezdokerdit);
        kezdokerdit.setBounds(50, 340, 110, 30);

        kredit.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        kredit.setForeground(new java.awt.Color(204, 0, 51));
        kezdokerdit1.add(kredit);
        kredit.setBounds(170, 300, 150, 30);

        jatekos.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jatekos.setForeground(new java.awt.Color(204, 0, 51));
        kezdokerdit1.add(jatekos);
        jatekos.setBounds(170, 260, 190, 30);

        vasarlas.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        vasarlas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        vasarlas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/mezovasarlas.png"))); // NOI18N
        vasarlas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vasarlas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vasarlasMouseClicked(evt);
            }
        });
        kezdokerdit1.add(vasarlas);
        vasarlas.setBounds(0, 660, 172, 64);

        kovetkezojatekosgomb.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        kovetkezojatekosgomb.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        kovetkezojatekosgomb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kovetkezojatekos.png"))); // NOI18N
        kovetkezojatekosgomb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kovetkezojatekosgomb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kovetkezojatekosgombMouseClicked(evt);
            }
        });
        kezdokerdit1.add(kovetkezojatekosgomb);
        kovetkezojatekosgomb.setBounds(180, 660, 172, 64);

        vasarlasara.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        vasarlasara.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kezdokerdit1.add(vasarlasara);
        vasarlasara.setBounds(0, 440, 350, 30);

        birtokoltmezoszama.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        birtokoltmezoszama.setForeground(new java.awt.Color(255, 255, 255));
        birtokoltmezoszama.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        birtokoltmezoszama.setText("Birtokolt mezők száma:");
        kezdokerdit1.add(birtokoltmezoszama);
        birtokoltmezoszama.setBounds(0, 90, 280, 40);

        nevkiir.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        nevkiir.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nevkiir.setText("Játékos:");
        kezdokerdit1.add(nevkiir);
        nevkiir.setBounds(50, 260, 110, 30);

        kezdokerdit2.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        kezdokerdit2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        kezdokerdit2.setText("Kredit:");
        kezdokerdit1.add(kezdokerdit2);
        kezdokerdit2.setBounds(50, 300, 110, 30);

        birtokoltmezo.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        birtokoltmezo.setForeground(new java.awt.Color(255, 255, 255));
        kezdokerdit1.add(birtokoltmezo);
        birtokoltmezo.setBounds(280, 100, 70, 30);

        kilepesPanel.setBackground(new java.awt.Color(255, 255, 255));
        kilepesPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        kilepesPanel.setDoubleBuffered(false);
        kilepesPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kilepesPanelMousePressed(evt);
            }
        });

        kilepesGomb.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        kilepesGomb.setForeground(new java.awt.Color(255, 255, 255));
        kilepesGomb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kilepesGomb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/Actions-window-close-icon.png"))); // NOI18N
        kilepesGomb.setToolTipText("Kilépés");
        kilepesGomb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kilepesGomb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kilepesGombMouseClicked(evt);
            }
        });

        infoGomb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoGomb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/info_32px.png"))); // NOI18N
        infoGomb.setToolTipText("Játékszabály");
        infoGomb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        infoGomb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                infoGombMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout kilepesPanelLayout = new javax.swing.GroupLayout(kilepesPanel);
        kilepesPanel.setLayout(kilepesPanelLayout);
        kilepesPanelLayout.setHorizontalGroup(
            kilepesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kilepesPanelLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(infoGomb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(kilepesGomb))
        );
        kilepesPanelLayout.setVerticalGroup(
            kilepesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kilepesPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(kilepesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kilepesGomb)
                    .addComponent(infoGomb)))
        );

        kezdokerdit1.add(kilepesPanel);
        kilepesPanel.setBounds(270, 0, 90, 50);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setMinimumSize(new java.awt.Dimension(350, 2));
        jPanel2.setPreferredSize(new java.awt.Dimension(350, 2));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        kezdokerdit1.add(jPanel2);
        jPanel2.setBounds(0, 250, 350, 2);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setMinimumSize(new java.awt.Dimension(350, 2));
        jPanel3.setPreferredSize(new java.awt.Dimension(350, 2));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        kezdokerdit1.add(jPanel3);
        jPanel3.setBounds(0, 480, 350, 2);

        javax.swing.GroupLayout hatterLayout = new javax.swing.GroupLayout(hatter);
        hatter.setLayout(hatterLayout);
        hatterLayout.setHorizontalGroup(
            hatterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hatterLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(kezdokerdit1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(hatterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(hatterLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        hatterLayout.setVerticalGroup(
            hatterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hatterLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(hatterLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(kezdokerdit1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(hatterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(hatterLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hatter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hatter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    /**
     * A a modellben generált számnak megfelelően megjeleníti a kockát.
     */
    private void rajzolKocka() {
        int dobas = Start.model.getKocka();
        String s = String.valueOf(dobas);
        System.out.println("dobás --> " + s);

        switch (dobas) {
            case 1:
                dobokocka.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/egy.png")));
                break;
            case 2:
                dobokocka.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/ketto.png")));
                break;
            case 3:
                dobokocka.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/harom.png")));
                break;
            case 4:
                dobokocka.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/negy.png")));
                break;
            case 5:
                dobokocka.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/ot.png")));
                break;
            case 6:
                dobokocka.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/hat.png")));
                break;
        };
    }

    /**
     * A modellnek megfelelően megjeleníti a tábla mezőin a játékosok bábuit
     * @param pos A játékosok pozícióit tároló tömb, ha -1 érték szerepel akkor a játékos nincs a táblán.
     */
    private void rajzolBabuk(int[] pos) {
        ArrayList<javax.swing.JLabel> sargaArrayList = new ArrayList<javax.swing.JLabel>(sargaCollection);
        ArrayList<javax.swing.JLabel> pirosArrayList = new ArrayList<javax.swing.JLabel>(pirosCollection);
        ArrayList<javax.swing.JLabel> kekArrayList = new ArrayList<javax.swing.JLabel>(kekCollection);
        ArrayList<javax.swing.JLabel> zoldArrayList = new ArrayList<javax.swing.JLabel>(zoldCollection);

        for (int i = 0; i <= 31; i++) {
            sargaArrayList.get(i).setVisible(false);
            pirosArrayList.get(i).setVisible(false);
            kekArrayList.get(i).setVisible(false);
            zoldArrayList.get(i).setVisible(false);
        }

        if (pos[0] != -1) {
            sargaArrayList.get(pos[0]).setVisible(true);
        }
        if (pos[1] != -1) {
            pirosArrayList.get(pos[1]).setVisible(true);
        }
        if (pos[2] != -1) {
            kekArrayList.get(pos[2]).setVisible(true);
        }
        if (pos[3] != -1) {
            zoldArrayList.get(pos[3]).setVisible(true);
        }
    }
    
    /**
     * "Neptun üzenete érkezett" felugró ablak megjelenítése.
     */
    private void rajzolNeptunUzenetJelzes() {
        NeptunUzenetJelzes t = new NeptunUzenetJelzes();
        t.setVisible(true);
        t.setLocationRelativeTo(null);
    }

    /**
     * A mezők tulajdonos jelző téglalapáainak megjelenítése a modellben szereplő adatok alapján.
     */
    private void rajzolTulaj() {
        ArrayList<javax.swing.JLabel> lista = new ArrayList<javax.swing.JLabel>(tulajCollection);

        int listaIndex = 0;
        int modelIndex = 1;
        while (listaIndex < 16) {
            int tulaj = Start.model.getMezonektulajdonosa(modelIndex);
            switch (tulaj) {
            case 0:
                lista.get(listaIndex).setBackground(new java.awt.Color(229, 217, 0));
                break;
            case 1:
                lista.get(listaIndex).setBackground(new java.awt.Color(236, 28, 36));
                break;
            case 2:
                lista.get(listaIndex).setBackground(new java.awt.Color(0, 0, 255));
                break;
            case 3:
                lista.get(listaIndex).setBackground(new java.awt.Color(14, 209, 69));
                break;
            }

            listaIndex += 1;
            modelIndex += 2;
        }
    }

    private void kiirMezo() {
        String s = Start.model.getMezo();
        mezonev.setText(s);
    }

    private void kiirMezoAra() {
        if (Integer.parseInt(Start.model.getMezoAra()) == 0) {
            vasarlasara.setText("Nem megvásárolható mező");
            vasarlas.setVisible(false);
        }
        if (Integer.parseInt(Start.model.getMezoAra()) > 0) {
            vasarlasara.setText("Mező ára: " + Start.model.getMezoAra() + " kredit");
        }
    }

    /**
     * A kocka "forgó" állapotába hozása. Felkészül a program a bábu léptetésére. Ilyenkor vállik klikkelhetővé.
     */
    private void kockaForog() {
            kovetkezojatekosgomb.setVisible(false);
            dobokocka.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/kockagif.gif")));
            jatekos.setText((String) Start.model.getName());
            kredit.setText(String.valueOf(Start.model.getKredit()));
            birtokoltmezo.setText(String.valueOf(Start.model.getBirtokoltMezoSzama()));
            kiirMezoAra();
            vasarlas.setVisible(false);
            kockaKlikkelheto = true;
    }

    /**
     * A kocka klikkelése. Ez által lépteti a játékos a bábuját a táblán.
     * @param evt 
     */
    private void dobokockaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dobokockaMouseClicked
        if (kockaKlikkelheto) {
            Start.model.dobas();
            rajzolKocka();
            Start.model.mozgat();
            mezonev.setText(Start.model.getMezo());
            rajzolBabuk(Start.model.poz());
            Start.model.mezoHatasa();
            if (Start.model.isKellMegjeleniteniNeptunt()) {
                rajzolNeptunUzenetJelzes();
                Start.model.setKellMegjeleniteniNeptunt(false);
            }
            jatekos.setText((String) Start.model.getName());
            kredit.setText(String.valueOf(Start.model.getKredit()));
            birtokoltmezo.setText(String.valueOf(Start.model.getBirtokoltMezoSzama()));
            kiirMezoAra();

            if (Start.model.isJatekVege()) {
				kovetkezojatekosgomb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/vegeajateknak.png")));
            };

            kovetkezojatekosgomb.setVisible(true);

            if (Start.model.getMezonektulajdonosa() == -1 && Start.model.vanElegendoKredit()) {
                vasarlas.setVisible(true);
            };
			
            kockaKlikkelheto = false;
        }
    }//GEN-LAST:event_dobokockaMouseClicked

    private void neptunUzenetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_neptunUzenetMouseClicked
    }//GEN-LAST:event_neptunUzenetMouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        setLocation(getX() + evt.getX() - mouseX, getY() + evt.getY() - mouseY);
    }//GEN-LAST:event_formMouseDragged

    private void vasarlasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vasarlasMouseClicked
        if (Start.model.getKredit() >= Integer.parseInt(Start.model.getMezoAra()) && Integer.parseInt(Start.model.getMezoAra()) > 0) {
            jatekos.setText((String) Start.model.getName());
            mezonev.setText(Start.model.getMezo());
            Start.model.mezoVasarlas();
            birtokoltmezo.setText(String.valueOf(Start.model.getBirtokoltMezoSzama()));
            kredit.setText(String.valueOf(Start.model.getKredit()));
            kiirMezoAra();
            kovetkezojatekosgomb.setVisible(true);
            vasarlas.setVisible(false);
            kockaKlikkelheto = false;
            rajzolTulaj();
        }
    }//GEN-LAST:event_vasarlasMouseClicked

    /**
     * A következő játékos gomb.
     * @param evt 
     */
    private void kovetkezojatekosgombMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kovetkezojatekosgombMouseClicked
        if (Start.model.isJatekVege()) {
            JatekVege jatekVege = new JatekVege();
            jatekVege.setVisible(true);
            jatekVege.setLocationRelativeTo(null);
            setVisible(false);
        };

        Start.model.kovJatekos();

        vasarlas.setVisible(false);

        kovetkezojatekosgomb.setVisible(false);
        jatekos.setText((String) Start.model.getName());
        mezonev.setText(Start.model.getMezo());
        kredit.setText(String.valueOf(Start.model.getKredit()));
        birtokoltmezo.setText(String.valueOf(Start.model.getBirtokoltMezoSzama()));
        vasarlasara.setVisible(true);
        kiirMezoAra();

        kockaForog();
    }//GEN-LAST:event_kovetkezojatekosgombMouseClicked

    private void kilepesPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kilepesPanelMousePressed

    }//GEN-LAST:event_kilepesPanelMousePressed

    private void kilepesGombMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kilepesGombMouseClicked
        System.exit(0);
    }//GEN-LAST:event_kilepesGombMouseClicked

    /**
     * Megjeleníti az információs ablakot a játék szabályairól.
     * @param evt 
     */
    private void infoGombMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoGombMouseClicked
        Informacio t = new Informacio();
        t.setVisible(true);
        t.setLocationRelativeTo(null);
    }//GEN-LAST:event_infoGombMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tabla().setVisible(true);
            }
        });
    }

    boolean kockaKlikkelheto = false;
    private Collection sargaCollection = new ArrayList();
    private Collection pirosCollection = new ArrayList();
    private Collection kekCollection = new ArrayList();
    private Collection zoldCollection = new ArrayList();
    private Collection tulajCollection = new ArrayList();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Kek1;
    private javax.swing.JLabel Kek10;
    private javax.swing.JLabel Kek11;
    private javax.swing.JLabel Kek12;
    private javax.swing.JLabel Kek13;
    private javax.swing.JLabel Kek14;
    private javax.swing.JLabel Kek15;
    private javax.swing.JLabel Kek16;
    private javax.swing.JLabel Kek17;
    private javax.swing.JLabel Kek18;
    private javax.swing.JLabel Kek19;
    private javax.swing.JLabel Kek2;
    private javax.swing.JLabel Kek20;
    private javax.swing.JLabel Kek21;
    private javax.swing.JLabel Kek22;
    private javax.swing.JLabel Kek23;
    private javax.swing.JLabel Kek24;
    private javax.swing.JLabel Kek25;
    private javax.swing.JLabel Kek26;
    private javax.swing.JLabel Kek27;
    private javax.swing.JLabel Kek28;
    private javax.swing.JLabel Kek29;
    private javax.swing.JLabel Kek3;
    private javax.swing.JLabel Kek30;
    private javax.swing.JLabel Kek31;
    private javax.swing.JLabel Kek32;
    private javax.swing.JLabel Kek4;
    private javax.swing.JLabel Kek5;
    private javax.swing.JLabel Kek6;
    private javax.swing.JLabel Kek7;
    private javax.swing.JLabel Kek8;
    private javax.swing.JLabel Kek9;
    private javax.swing.JLabel Mezo10;
    private javax.swing.JLabel Mezo12;
    private javax.swing.JLabel Mezo14;
    private javax.swing.JLabel Mezo16;
    private javax.swing.JLabel Mezo18;
    private javax.swing.JLabel Mezo2;
    private javax.swing.JLabel Mezo20;
    private javax.swing.JLabel Mezo22;
    private javax.swing.JLabel Mezo24;
    private javax.swing.JLabel Mezo26;
    private javax.swing.JLabel Mezo28;
    private javax.swing.JLabel Mezo30;
    private javax.swing.JLabel Mezo32;
    private javax.swing.JLabel Mezo4;
    private javax.swing.JLabel Mezo6;
    private javax.swing.JLabel Mezo8;
    private javax.swing.JLabel Piros1;
    private javax.swing.JLabel Piros10;
    private javax.swing.JLabel Piros11;
    private javax.swing.JLabel Piros12;
    private javax.swing.JLabel Piros13;
    private javax.swing.JLabel Piros14;
    private javax.swing.JLabel Piros15;
    private javax.swing.JLabel Piros16;
    private javax.swing.JLabel Piros17;
    private javax.swing.JLabel Piros18;
    private javax.swing.JLabel Piros19;
    private javax.swing.JLabel Piros2;
    private javax.swing.JLabel Piros20;
    private javax.swing.JLabel Piros21;
    private javax.swing.JLabel Piros22;
    private javax.swing.JLabel Piros23;
    private javax.swing.JLabel Piros24;
    private javax.swing.JLabel Piros25;
    private javax.swing.JLabel Piros26;
    private javax.swing.JLabel Piros27;
    private javax.swing.JLabel Piros28;
    private javax.swing.JLabel Piros29;
    private javax.swing.JLabel Piros3;
    private javax.swing.JLabel Piros30;
    private javax.swing.JLabel Piros31;
    private javax.swing.JLabel Piros32;
    private javax.swing.JLabel Piros4;
    private javax.swing.JLabel Piros5;
    private javax.swing.JLabel Piros6;
    private javax.swing.JLabel Piros7;
    private javax.swing.JLabel Piros8;
    private javax.swing.JLabel Piros9;
    private javax.swing.JLabel Sarga1;
    private javax.swing.JLabel Sarga10;
    private javax.swing.JLabel Sarga11;
    private javax.swing.JLabel Sarga12;
    private javax.swing.JLabel Sarga13;
    private javax.swing.JLabel Sarga14;
    private javax.swing.JLabel Sarga15;
    private javax.swing.JLabel Sarga16;
    private javax.swing.JLabel Sarga17;
    private javax.swing.JLabel Sarga18;
    private javax.swing.JLabel Sarga19;
    private javax.swing.JLabel Sarga2;
    private javax.swing.JLabel Sarga20;
    private javax.swing.JLabel Sarga21;
    private javax.swing.JLabel Sarga22;
    private javax.swing.JLabel Sarga23;
    private javax.swing.JLabel Sarga24;
    private javax.swing.JLabel Sarga25;
    private javax.swing.JLabel Sarga26;
    private javax.swing.JLabel Sarga27;
    private javax.swing.JLabel Sarga28;
    private javax.swing.JLabel Sarga29;
    private javax.swing.JLabel Sarga3;
    private javax.swing.JLabel Sarga30;
    private javax.swing.JLabel Sarga31;
    private javax.swing.JLabel Sarga32;
    private javax.swing.JLabel Sarga4;
    private javax.swing.JLabel Sarga5;
    private javax.swing.JLabel Sarga6;
    private javax.swing.JLabel Sarga7;
    private javax.swing.JLabel Sarga8;
    private javax.swing.JLabel Sarga9;
    private javax.swing.JLabel Tabla;
    private javax.swing.JLabel Zold1;
    private javax.swing.JLabel Zold10;
    private javax.swing.JLabel Zold11;
    private javax.swing.JLabel Zold12;
    private javax.swing.JLabel Zold13;
    private javax.swing.JLabel Zold14;
    private javax.swing.JLabel Zold15;
    private javax.swing.JLabel Zold16;
    private javax.swing.JLabel Zold17;
    private javax.swing.JLabel Zold18;
    private javax.swing.JLabel Zold19;
    private javax.swing.JLabel Zold2;
    private javax.swing.JLabel Zold20;
    private javax.swing.JLabel Zold21;
    private javax.swing.JLabel Zold22;
    private javax.swing.JLabel Zold23;
    private javax.swing.JLabel Zold24;
    private javax.swing.JLabel Zold25;
    private javax.swing.JLabel Zold26;
    private javax.swing.JLabel Zold27;
    private javax.swing.JLabel Zold28;
    private javax.swing.JLabel Zold29;
    private javax.swing.JLabel Zold3;
    private javax.swing.JLabel Zold30;
    private javax.swing.JLabel Zold31;
    private javax.swing.JLabel Zold32;
    private javax.swing.JLabel Zold4;
    private javax.swing.JLabel Zold5;
    private javax.swing.JLabel Zold6;
    private javax.swing.JLabel Zold7;
    private javax.swing.JLabel Zold8;
    private javax.swing.JLabel Zold9;
    private javax.swing.JLabel birtokoltmezo;
    private javax.swing.JLabel birtokoltmezoszama;
    private javax.swing.JLabel dobokocka;
    private javax.swing.JPanel hatter;
    private javax.swing.JLabel infoGomb;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel jatekos;
    private javax.swing.JLabel kezdokerdit;
    private javax.swing.JPanel kezdokerdit1;
    private javax.swing.JLabel kezdokerdit2;
    private javax.swing.JLabel kilepesGomb;
    private javax.swing.JPanel kilepesPanel;
    private javax.swing.JLabel kovetkezojatekosgomb;
    private javax.swing.JLabel kredit;
    private javax.swing.JLabel mezonev;
    private javax.swing.JLabel neptunUzenet;
    private javax.swing.JLabel nevkiir;
    private javax.swing.JLabel vasarlas;
    private javax.swing.JLabel vasarlasara;
    // End of variables declaration//GEN-END:variables

    private void println(Random rand) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void buildCollections() {
        sargaCollection.add(Sarga1);
        sargaCollection.add(Sarga2);
        sargaCollection.add(Sarga3);
        sargaCollection.add(Sarga4);
        sargaCollection.add(Sarga5);
        sargaCollection.add(Sarga6);
        sargaCollection.add(Sarga7);
        sargaCollection.add(Sarga8);
        sargaCollection.add(Sarga9);
        sargaCollection.add(Sarga10);
        sargaCollection.add(Sarga11);
        sargaCollection.add(Sarga12);
        sargaCollection.add(Sarga13);
        sargaCollection.add(Sarga14);
        sargaCollection.add(Sarga15);
        sargaCollection.add(Sarga16);
        sargaCollection.add(Sarga17);
        sargaCollection.add(Sarga18);
        sargaCollection.add(Sarga19);
        sargaCollection.add(Sarga20);
        sargaCollection.add(Sarga21);
        sargaCollection.add(Sarga22);
        sargaCollection.add(Sarga23);
        sargaCollection.add(Sarga24);
        sargaCollection.add(Sarga25);
        sargaCollection.add(Sarga26);
        sargaCollection.add(Sarga27);
        sargaCollection.add(Sarga28);
        sargaCollection.add(Sarga29);
        sargaCollection.add(Sarga30);
        sargaCollection.add(Sarga31);
        sargaCollection.add(Sarga32);
        zoldCollection.add(Zold1);
        zoldCollection.add(Zold2);
        zoldCollection.add(Zold3);
        zoldCollection.add(Zold4);
        zoldCollection.add(Zold5);
        zoldCollection.add(Zold6);
        zoldCollection.add(Zold7);
        zoldCollection.add(Zold8);
        zoldCollection.add(Zold9);
        zoldCollection.add(Zold10);
        zoldCollection.add(Zold11);
        zoldCollection.add(Zold12);
        zoldCollection.add(Zold13);
        zoldCollection.add(Zold14);
        zoldCollection.add(Zold15);
        zoldCollection.add(Zold16);
        zoldCollection.add(Zold17);
        zoldCollection.add(Zold18);
        zoldCollection.add(Zold19);
        zoldCollection.add(Zold20);
        zoldCollection.add(Zold21);
        zoldCollection.add(Zold22);
        zoldCollection.add(Zold23);
        zoldCollection.add(Zold24);
        zoldCollection.add(Zold25);
        zoldCollection.add(Zold26);
        zoldCollection.add(Zold27);
        zoldCollection.add(Zold28);
        zoldCollection.add(Zold29);
        zoldCollection.add(Zold30);
        zoldCollection.add(Zold31);
        zoldCollection.add(Zold32);
        kekCollection.add(Kek1);
        kekCollection.add(Kek2);
        kekCollection.add(Kek3);
        kekCollection.add(Kek4);
        kekCollection.add(Kek5);
        kekCollection.add(Kek6);
        kekCollection.add(Kek7);
        kekCollection.add(Kek8);
        kekCollection.add(Kek9);
        kekCollection.add(Kek10);
        kekCollection.add(Kek11);
        kekCollection.add(Kek12);
        kekCollection.add(Kek13);
        kekCollection.add(Kek14);
        kekCollection.add(Kek15);
        kekCollection.add(Kek16);
        kekCollection.add(Kek17);
        kekCollection.add(Kek18);
        kekCollection.add(Kek19);
        kekCollection.add(Kek20);
        kekCollection.add(Kek21);
        kekCollection.add(Kek22);
        kekCollection.add(Kek23);
        kekCollection.add(Kek24);
        kekCollection.add(Kek25);
        kekCollection.add(Kek26);
        kekCollection.add(Kek27);
        kekCollection.add(Kek28);
        kekCollection.add(Kek29);
        kekCollection.add(Kek30);
        kekCollection.add(Kek31);
        kekCollection.add(Kek32);
        pirosCollection.add(Piros1);
        pirosCollection.add(Piros2);
        pirosCollection.add(Piros3);
        pirosCollection.add(Piros4);
        pirosCollection.add(Piros5);
        pirosCollection.add(Piros6);
        pirosCollection.add(Piros7);
        pirosCollection.add(Piros8);
        pirosCollection.add(Piros9);
        pirosCollection.add(Piros10);
        pirosCollection.add(Piros11);
        pirosCollection.add(Piros12);
        pirosCollection.add(Piros13);
        pirosCollection.add(Piros14);
        pirosCollection.add(Piros15);
        pirosCollection.add(Piros16);
        pirosCollection.add(Piros17);
        pirosCollection.add(Piros18);
        pirosCollection.add(Piros19);
        pirosCollection.add(Piros20);
        pirosCollection.add(Piros21);
        pirosCollection.add(Piros22);
        pirosCollection.add(Piros23);
        pirosCollection.add(Piros24);
        pirosCollection.add(Piros25);
        pirosCollection.add(Piros26);
        pirosCollection.add(Piros27);
        pirosCollection.add(Piros28);
        pirosCollection.add(Piros29);
        pirosCollection.add(Piros30);
        pirosCollection.add(Piros31);
        pirosCollection.add(Piros32);

        tulajCollection.add(Mezo2);
        tulajCollection.add(Mezo4);
        tulajCollection.add(Mezo6);
        tulajCollection.add(Mezo8);
        tulajCollection.add(Mezo10);
        tulajCollection.add(Mezo12);
        tulajCollection.add(Mezo14);
        tulajCollection.add(Mezo16);
        tulajCollection.add(Mezo18);
        tulajCollection.add(Mezo20);
        tulajCollection.add(Mezo22);
        tulajCollection.add(Mezo24);
        tulajCollection.add(Mezo26);
        tulajCollection.add(Mezo28);
        tulajCollection.add(Mezo30);
        tulajCollection.add(Mezo32);
    }
}
